apiVersion: v2
name: purgehistoconsos-job
description: Helm chart for purgehistoconsos-job in serviceeligibility service.
type: application
appVersion: "${imageTag}"
version: 0.0.0
dependencies:
  - name: helm-chart-beyond-common
    repository: "@beyond"
    version: v15.1.6
