spring:
  application:
    name: extractpopulation-job
  data:
    mongodb:
      uri: ${BDD_MONGODB_URL:${MONGODB_URL}}
beyond:
  event:
    group-id: ${CLOUD_PROVIDER:notConfigured}-${TARGET_ENV:notConfigured}-bdd-extractpopulation-job
  management-scope:
    enabled: false
  observability:
    log:
      enabled: true
