apiVersion: v2
name: otp-search-func
description: A Helm chart for Kubernetes
type: application
version: 0.0.0
appVersion: "${imageTag}"
dependencies:
  - name: helm-chart-beyond-common
    repository: "oci://registry-dev.beyond.cegedim.cloud/devops-infra"
    version: v16.0.7
