MONGODB_DATABASE_NAME: next-serviceeligibility-core-api
MONGODB_URL: mongodb://localhost:27017

CLIENT_ID: test-es16
CLIENT_SECRET: nn6SAeEsmeij97djO5bSHs6rEjdw5cgd
keycloak.url: https://idp.dev.beyond.cegedim.cloud/auth
keycloak.realm: htp

COMMON_INDEX_BASENAME: h-blue-5729
CSV_DELIMITER: ;
CSV_OUTPUT_DIRECTORY: C:/tmp/_facturation
ELASTICSEARCH_LOGIN: login
ELASTICSEARCH_PASSWORD: password
ELASTICSEARCH_URL: https://beyond-data-dev.es.cegedim.cloud
FQDN: ''
KAFKA_SERVERS: localhost:9092

TARGET_ENV: local
ZIPKIN_URL: https://jaeger-collector.dev.beyond.cegedim.cloud
audit:
  schema:
    url: https://documentation.beyond-by-cegedim.com/schemas/audits
beyond:
  couloir: htp
  customer: editeur
  instance: htp-es15
  observability:
    log:
      enabled: false
    tracing:
      enabled: false
kafka:
  topic:
    beyond-events: events
keycloak:
  enabled: false
logging:
  level:
    com:
      cegedim: debug
      cegedim.common.base.log: info
schema:
  path: path
  url: https://beyond-by-cegedim.com/schemas/events
server:
  port: 8081
service:
  code: serviceeligibility
socle:
  code: Insurance
spring:
  aop:
    proxy-target-class: true
  application:
    name: facturation-htp-job
zipkin:
  sender:
    type: web
  service:
    name: ${spring.application.name}
