MONGODB_URL: mongodb://localhost:27017
MONGODB_DATABASE_NAME: next-serviceeligibility-core-api
BDD_MONGODB_URL: mongodb://localhost:27017/next-serviceeligibility-core-api

CLIENT_ID: test-es16
CLIENT_SECRET: nn6SAeEsmeij97djO5bSHs6rEjdw5cgd
keycloak.url: https://idp.dev.beyond.cegedim.cloud/auth
keycloak.realm: htp

ARL_FOLDER: C:/workdir/arlfiles
BEYOND_COULOIR: htp-es15
BEYOND_CUSTOMER: editeur
BEYOND_INSTANCE: htp-es15
CLOUD_PROVIDER: home
COMMON_INDEX_BASENAME: local
ELASTICSEARCH_LOGIN: login
ELASTICSEARCH_PASSWORD: password
ELASTICSEARCH_URL: https://beyond-data-dev.es.cegedim.cloud
KAFKA_SERVERS: localhost:9092
MAXIMUM_REJECT_LIST_SIZE: '5000'
OUTPUT_FOLDER: C:/workdir/out_almerys/
SEND_EVENTS: false
TARGET_DOMAIN: dev
TARGET_ENV: local
audit:
  schema:
    url: https://documentation.beyond-by-cegedim.com/schemas/audits
beyond:
  couloir: htp
  customer: editeur
  instance: htp-es15
  observability:
    log:
      enabled: false
kafka:
  topic:
    beyond-events: events
keycloak:
  enabled: true
logging:
  level:
    com:
      cegedim:
        next:
          serviceeligibility:
            almerys608: debug
schema:
  path: Insurance/serviceeligibility
  url: https://documentation.beyond-by-cegedim.com/schemas/schemas/release/pi14/events
server:
  port: 8090
service:
  code: serviceeligibility
socle:
  code: Insurance
