image:
  registry: "${imageRegistry}"
  repository: "${imageRepository}"
  tag: "${imageTag}"
  pullPolicy: IfNotPresent
livenessProbe:
  failureThreshold: 30
  httpGet:
    path: /actuator/health
    port: http
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /actuator/ready
    port: http
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10
resources: {}
service:
  enabled: true
env:
  COMPONENT_NAME: "blue-7198"
