BDD_MONGODB_URL: mongodb://localhost:27017/next-serviceeligibility-core-api
MONGODB_URL: mongodb://localhost:27017
MONGODB_DATABASE_NAME: next-serviceeligibility-core-api

CLIENT_ID: test-es16
CLIENT_SECRET: nn6SAeEsmeij97djO5bSHs6rEjdw5cgd
keycloak.url: https://idp.dev.beyond.cegedim.cloud/auth
keycloak.realm: htp

CLOUD_PROVIDER: itcare
TARGET_DOMAIN: dev
TARGET_ENV: local

COMMON_INDEX_BASENAME: local
ELASTICSEARCH_LOGIN: login
ELASTICSEARCH_PASSWORD: password
ELASTICSEARCH_URL: https://beyond-data-dev.es.cegedim.cloud

KAFKA_SERVERS: localhost:9092
KAFKA_TOPIC_BDD-BENEFAI: bdd-benefai
KAFKA_TOPIC_BDD-PRESTIJ: prestij

SEND_EVENTS: 'false'

audit:
  schema:
    url: https://documentation.beyond-by-cegedim.com/schemas/audits
schema:
  path: =Insurance/serviceeligibility
  url: https://documentation.beyond-by-cegedim.com/schemas/schemas/release/pi14/events
kafka:
  topic:
    beyond-events: events

beyond:
  couloir: htp
  customer: editeur
  instance: htp-es15
  observability:
    tracing:
      enabled: false
    log:
      enabled: false

logging:
  level:
    com:
      cegedim: debug

server:
  port: '8084'
  servlet:
    context-path: /serviceeligibility/prestij/worker
service:
  code: serviceeligibility
socle:
  code: Insurance

s3_access_key: nzua4ydzoc19biobbyqz
s3_bucket: cegedim-beyond-dev-rp-14-htp-msdata
s3_file_path: insurance/organisation/setting-scopes/scopes.json
s3_host: storage-et1.cloud.cegedim.com
s3_mls_folder_path: insurance/organisation/mls-config/
s3_orga_admin_data_path: insurance/organisation/organisations-admin-data/
s3_region: eu-west-1
s3_secret_access_key: NiVJi/CZj/wH2Bbg38+1pGL+In9VvHbi8yYBlRYw
s3_secure: true
