ACTIVATED: true
WORKDIR_INPUT_FOLDER: C:/workdir/in_almerys/
WORKDIR_OUTPUT_FOLDER: C:/workdir/out_almerys/
MONGODB_DATABASE_NAME: next-serviceeligibility-core-api
MONGODB_URL: mongodb://localhost:27017
CLIENT_ID: test-es16
CLIENT_SECRET: nn6SAeEsmeij97djO5bSHs6rEjdw5cgd
CLIENT_TYPE: INSURER
ELASTICSEARCH_LOGIN: login
ELASTICSEARCH_PASSWORD: password
ELASTICSEARCH_URL: https://beyond-data-dev.es.cegedim.cloud
logging:
  level:
    com:
      cegedim:
        next: debug
beyond:
  couloir: htp
  customer: editeur
  instance: htp-es15
  observability:
    log:
      enabled: false
    tracing:
      enabled: false
keycloak:
  enabled: false
spring:
  aop:
    proxy-target-class: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.dev.beyond.cegedim.cloud/auth/realms/htp
