beyond:
  messaging:
    types:
      BenefAIV5: com.cegedim.next.serviceeligibility.core.model.kafka.contratv5.BenefAIV5
    security-context:
      enabled: false
    transactional: false
    cloudEvent:
      enabled: true
  event:
    group-id: ${CLOUD_PROVIDER:notConfigured}-${TARGET_ENV:notConfigured}-bdd-reprise-beneficiaires
  management-scope:
    enabled: false
  observability:
    log:
      enabled: true
endpoints:
  enabled: false
logging:
  level:
    com:
      cegedim:
        common:
          base:
            log: error
server:
  compression:
    enabled: true
    mime-types: application/json
  error:
    path: servererror
    whitelabel:
      enabled: false
  forward-headers-strategy: framework
  http2:
    enabled: true
spring:
  application:
    name: reprise-beneficiaires-job
  data:
    mongodb:
      uri: ${BDD_MONGODB_URL:${MONGODB_URL}}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
kafka:
  topic:
    beyond-events: beyond-events
