BDD_MONGODB_URL: mongodb://localhost:27017/next-serviceeligibility-core-api
CLOUD_PROVIDER: home
COMMON_INDEX_BASENAME: local
ELASTICSEARCH_LOGIN: login
ELASTICSEARCH_PASSWORD: password
ELASTICSEARCH_URL: https://beyond-data-dev.es.cegedim.cloud
KAFKA_SERVERS: localhost:9092
SEND_EVENTS: 'false'
TARGET_ENV: local
audit:
  schema:
    url: https://documentation.beyond-by-cegedim.com/schemas/audits
beyond:
  couloir: htp
  customer: editeur
  instance: htp-es15
logging:
  level:
    com:
      cegedim: debug
schema:
  path: Insurance/serviceeligibility
  url: https://documentation.beyond-by-cegedim.com/schemas/schemas/release/pi14/events
server:
  port: '8090'
service:
  code: serviceeligibility
socle:
  code: Insurance
