JOB_SPAN_NAME: serviceeligibility-batch620-job
beyond:
  caching:
    specs:
      parametreCache:
        expireAfterAccessDuration: PT2M
        maxSize: 50
        type: caffeine
  event:
    group-id: ${CLOUD_PROVIDER:notConfigured}-${TARGET_ENV:notConfigured}-bdd-batch620-job
  messaging:
    transactional: false
    cloudEvent:
      enabled: false
    security-context:
      enabled: false
  management-scope:
    enabled: false
logging:
  level:
    org:
      springframework:
        data:
          convert:
            CustomConversions: ERROR
spring:
  application:
    name: serviceeligibility-batch620-job
  data:
    mongodb:
      uri: ${BDD_MONGODB_URL:${MONGODB_URL}}
