beyond:
  caching:
    specs:
      bobb:
        expireAfterAccessDuration: PT2M
        maxSize: 50
        type: caffeine
      referentialCacheRDO:
        expireAfterAccessDuration: PT2M
        maxSize: 50
        type: caffeine
      parametreCarteTPCache:
        expireAfterAccessDuration: PT2M
        maxSize: 50
        type: caffeine
  event:
    group-id: ${CLOUD_PROVIDER:notConfigured}-${TARGET_ENV:notConfigured}-bdd-rdoserviceprestation-job
  management-scope:
    enabled: false
  observability:
    tracing:
      enabled:
        enabled: false
  messaging:
    enabled: true
    encoding: binary
    security-context:
      enabled: false
    types:
      BenefAIV5: com.cegedim.next.serviceeligibility.core.model.kafka.contratv5.BenefAIV5
      BeneficiaireId: com.cegedim.next.serviceeligibility.core.model.kafka.benef.BeneficiaireId
      RecipientsMessageDto: com.cegedim.beyond.schemas.RecipientsMessageDto
      String: java.lang.String
      TriggerId: com.cegedim.next.serviceeligibility.core.model.kafka.TriggerId
      UndueRetentionMessageDto: com.cegedim.beyond.schemas.UndueRetentionMessageDto
    transactional: false
  security:
    client:
      enabled: true
      rest-template:
        enabled: true
    server:
      enabled: true
logging:
  level:
    com:
      cegedim:
        common:
          base:
            log: error
server:
  compression:
    enabled: true
    mime-types: application/json
  error:
    path: servererror
    whitelabel:
      enabled: false
  forward-headers-strategy: framework
  http2:
    enabled: true
spring:
  application:
    name: serviceeligibility-rdoserviceprestation-job
  data:
    mongodb:
      uri: ${BDD_MONGODB_URL:${MONGODB_URL}}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  main:
    web-application-type: servlet
