apiVersion: v2
name: extractbenefsansdroitstp-job
description: Helm chart for extractbenefsansdroitstp-job in serviceeligibility service.
type: application
appVersion: "${imageTag}"
version: 0.0.0
dependencies:
  - name: helm-chart-beyond-common
    repository: "oci://registry-dev.beyond.cegedim.cloud/devops-infra"
    version: v16.0.7
