apiVersion: v2
name: blue-7214
description: Helm chart for blue-7214 in serviceeligibility service.
type: application
appVersion: "${imageTag}"
version: 0.0.0
dependencies:
  - name: helm-chart-beyond-common
    repository: "oci://registry-dev.beyond.cegedim.cloud/devops-infra"
    version: v16.0.7
