BDD_MONGODB_URL: mongodb://localhost:27017/next-serviceeligibility-core-api
MONGODB_URL: mongodb://localhost:27017
MONGODB_DATABASE_NAME: next-serviceeligibility-core-api

CLIENT_ID: test-es16
CLIENT_SECRET: nn6SAeEsmeij97djO5bSHs6rEjdw5cgd
keycloak.url: https://idp.dev.beyond.cegedim.cloud/auth
keycloak.realm: htp

CLOUD_PROVIDER: home
BEYOND_COULOIR: htp-es15
BEYOND_CUSTOMER: editeur
BEYOND_INSTANCE: htp-es15
TARGET_ENV: local

COMMON_INDEX_BASENAME: local
CONTROLE_CORRESPONDANCE_BOBB: true
CONTROLE_METIER_HTP: true
ELASTICSEARCH_LOGIN: login
ELASTICSEARCH_PASSWORD: password
ELASTICSEARCH_URL: https://beyond-data-dev.es.cegedim.cloud

KAFKA_SERVERS: localhost:9092

allowTestingEndPoints: 'true'
BATCH_SIZE: '10000'
environment: local
keycloak_realm: htp
ORGA_LIB_ENABLED: true
PW_API_NB_RESULT_PER_PAGE: 10
PW_API_URL: https://htp-es15.dev.beyond.cegedim.cloud/engine/core/api
PW_OFFERSTRUCTURE_VERSION: 'V4'
SEND_EVENTS: false
SEND_RECIPIENT_MESSAGE: false
SETTINGS_API_URL: https://htp-es15.dev.beyond.cegedim.cloud/settingsui
REFERENTIAL_API_URL: https://htp-es15.dev.beyond.cegedim.cloud/referential/core/api
TRANSACTIONNAL: true


audit:
  schema:
    url: https://documentation.beyond-by-cegedim.com/schemas/audits
schema:
  path: Insurance/serviceeligibility
  url: https://documentation.beyond-by-cegedim.com/schemas/schemas/release/pi14/events
kafka:
  topic:
    beyond-events: events
    bdds-to-blb-beneficiary-feeding: blb
    bdd-contract: bdd-contract
    bdd-extract-contract: bdd-extract-contract
    bdd-demande-declaration: bdd-demande-declaration
beyond:
  event:
    group-id: toto
  observability:
    tracing:
      enabled: false
    log:
      enabled: false
  management-scope:
    enabled: false
logging:
  level:
    com:
      cegedim:
        next: debug

server:
  port: 8081
  servlet:
    context-path: /serviceeligibility/consumer/worker
service:
  code: serviceeligibility
socle:
  code: Insurance

s3_access_key: nzua4ydzoc19biobbyqz
s3_bucket: cegedim-beyond-dev-htp-es15-msdata
s3_file_path: insurance/organisation/setting-scopes/scopes.json
s3_host: storage-et1.cloud.cegedim.com
s3_orga_admin_data_path: insurance/organisation/organisations-admin-data/
s3_region: eu-west-1
s3_secret_access_key: NiVJi/CZj/wH2Bbg38+1pGL+In9VvHbi8yYBlRYw
s3_secure: true

# For redis cache
REDIS_ADMIN_PASSWORD: password
REDIS_ADMIN_USER: redis
REDIS_AGENT_NODE_0: detcisedtrd001.hosting.cegedim.cloud
REDIS_AGENT_NODE_1: detcisedtrd002.hosting.cegedim.cloud
REDIS_AGENT_NODE_2: detcisedtrd003.hosting.cegedim.cloud
REDIS_CRT_PATH: ${user.home}/.redis/redis.truststore.crt
REDIS_MASTER: detcisedtrd01
REDIS_PASSWORD: password
REDIS_PORT: 26379
REDIS_USER: redis
