BDD_MONGODB_URL: mongodb://localhost:27017/next-serviceeligibility-core-api
MONGODB_URL: mongodb://localhost:27017
MONGODB_DATABASE_NAME: next-serviceeligibility-core-api

CLIENT_ID: test-es16
CLIENT_SECRET: nn6SAeEsmeij97djO5bSHs6rEjdw5cgd
keycloak.url: https://idp.dev.beyond.cegedim.cloud/auth
keycloak.realm: htp

CLOUD_PROVIDER: itcare
TARGET_DOMAIN: dev
TARGET_ENV: local

COMMON_INDEX_BASENAME: local
ELASTICSEARCH_LOGIN: login
ELASTICSEARCH_PASSWORD: password
ELASTICSEARCH_URL: https://beyond-data-dev.es.cegedim.cloud

CONSUMER_GROUP_ID_NAME: demandeDeclaration
KAFKA_SERVERS: localhost:9092
KAFKA_TOPIC_BDD-CONTRATTP: 'bdd-contrattp'
KAFKA_TOPIC_BDD-DEMANDE-DECLARATION: 'demandeDeclaration'
KAFKA_TOPIC_BDD-DEMANDE-ABANDON-TRIGGER: 'demandeAbandonTrigger'
KAFKA_TOPIC_BDD-DEMANDE-RENOUVELLEMENT-DECLARATION: 'demandeRenouvellementDeclaration'
KAFKA_TOPIC_BDD-DEMANDE-RENOUVELLEMENT-DECLARATION-UNITAIRE: 'demandeRenouvellementDeclarationUnitaire'
KAFKA_TOPIC_BDD-RECIPIENTS-REQUEST: 'bdd-recipients-request'
KAFKA_TOPIC_BDD-UNDUE-RETENTION: 'bdd-undue-retention'
KAFKA_TOPIC_BDD-UPDATE-RENOUVELLEMENT-DECLARATION: 'updateRenouvellementDeclaration'

SEND_EVENTS: 'false'
environment: local
keycloak_realm: htp


audit:
  schema:
    url: https://documentation.beyond-by-cegedim.com/schemas/audits
schema:
  path: Insurance/serviceeligibility
  url: https://documentation.beyond-by-cegedim.com/schemas/schemas/release/pi14/events
kafka:
  topic:
    beyond-events: events
    bdd-demande-renouvellement-declaration: bdd-demande-renouvellement-declaration
    bdd-update-renouvellement-declaration: bdd-update-renouvellement-declaration

beyond:
  couloir: htp
  customer: editeur
  instance: htp-es15
  observability:
    tracing:
      enabled: false
    log:
      enabled: false
  management-scope:
    enabled: false
logging:
  level:
    com:
      cegedim: debug

server:
  port: '8086'
  servlet:
    context-path: /serviceeligibility/triggerrenouvellement/worker
service:
  code: serviceeligibility
socle:
  code: Insurance

s3_access_key: nzua4ydzoc19biobbyqz
s3_bucket: cegedim-beyond-dev-htp-es15-msdata
s3_file_path: insurance/organisation/setting-scopes/scopes.json
s3_host: storage-et1.cloud.cegedim.com
s3_orga_admin_data_path: insurance/organisation/organisations-admin-data/
s3_region: eu-west-1
s3_secret_access_key: NiVJi/CZj/wH2Bbg38+1pGL+In9VvHbi8yYBlRYw
s3_secure: true
