BDD_MONGODB_URL: mongodb://localhost:27017/next-serviceeligibility-core-api
MONGODB_URL: mongodb://localhost:27017
MONGODB_DATABASE_NAME: next-serviceeligibility-core-api

CLIENT_ID: test-es16
CLIENT_SECRET: nn6SAeEsmeij97djO5bSHs6rEjdw5cgd
keycloak.url: https://idp.dev.beyond.cegedim.cloud/auth
keycloak.realm: htp

CLOUD_PROVIDER: itcare
COMMON_INDEX_BASENAME: local
KAFKA_SERVERS: localhost:9092
SEND_EVENTS: 'false'
TARGET_DOMAIN: dev
TARGET_ENV: local
WORKDIR_PATH: C:/workdir/
audit:
  schema:
    url: https://documentation.beyond-by-cegedim.com/schemas/audits
beyond:
  couloir: htp
  customer: editeur
  instance: htp-es15
  observability:
    log:
      enabled: false
    tracing:
      enabled: false
kafka:
  topic:
    beyond-events: events
logging:
  level:
    com:
      cegedim: debug
schema:
  path: Insurance/serviceeligibility
  url: https://documentation.beyond-by-cegedim.com/schemas/schemas/release/pi14/events
server:
  port: '8090'
service:
  code: serviceeligibility
socle:
  code: Insurance
