server:
  compression:
    enabled: true
    mime-types: application/json
  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: false
    path: servererror
  http2:
    enabled: true
spring:
  application:
    name: consolidationcontract-job
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  data:
    mongodb:
      uri: ${BDD_MONGODB_URL:${MONGODB_URL}}
beyond:
  event:
    group-id: ${CLOUD_PROVIDER:notConfigured}-${TARGET_ENV:notConfigured}-bdd-consolidationcontract-job
  management-scope:
    enabled: false
  messaging:
    transactional: false
  observability:
    tracing:
      enabled:
        enabled: false
  caching:
    specs:
      contrat634:
        expireAfterAccessDuration: PT2M
        maxSize: 50
        type: caffeine
logging:
  level:
    com:
      cegedim:
        common:
          base:
            log: error
