MONGODB_URL: mongodb://localhost:27017
MONGODB_DATABASE_NAME: next-serviceeligibility-core-api
BDD_MONGODB_URL: mongodb://localhost:27017/next-serviceeligibility-core-api

CLIENT_ID: test-es16
CLIENT_SECRET: nn6SAeEsmeij97djO5bSHs6rEjdw5cgd
keycloak.url: https://idp.dev.beyond.cegedim.cloud/auth
keycloak.realm: htp

beyond:
  couloir: htp
  customer: editeur
  instance: htp-es15
COMMON_INDEX_BASENAME: h-blue-5729
ELASTICSEARCH_LOGIN: login
ELASTICSEARCH_PASSWORD: password
ELASTICSEARCH_URL: https://beyond-data-dev.es.cegedim.cloud
FQDN: ''
KAFKA_SERVERS: localhost:9092
TARGET_ENV: local
ZIPKIN_URL: https://jaeger-collector.dev.beyond.cegedim.cloud
audit:
  schema:
    url: https://documentation.beyond-by-cegedim.com/schemas/audits
kafka:
  topic:
    beyond-events: events
keycloak:
  enabled: false
logging:
  level:
    com:
      cegedim: debug
      cegedim.common.base.log: info
schema:
  path: path
  url: https://beyond-by-cegedim.com/schemas/events
server:
  port: 8081
service:
  code: serviceeligibility
socle:
  code: Insurance
spring:
  aop:
    proxy-target-class: true
  application:
    name: purgehistoconsos-job
zipkin:
  sender:
    type: web
  service:
    name: ${spring.application.name}
s3_access_key: nzua4ydzoc19biobbyqz
s3_bucket: cegedim-beyond-dev-htp-es15-msdata
s3_connection_timeout: '900'
s3_host: storage-et1.cloud.cegedim.com
s3_port: '0'
s3_region: eu-west-1
s3_secret_access_key: NiVJi/CZj/wH2Bbg38+1pGL+In9VvHbi8yYBlRYw
s3_secure: true
s3_write_timeout: '900'
proxy:
  host: "#"
  port: "0"
